### ISSUE TITLE
Add missing info and make this repo similar to the existing rust-vmm projects

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/xen-sys#1]
For this we can use the crate-template to identify the missing things: https://github.com/rust-vmm/crate-template/. Typical suspects are the CODEOWNERS file and the [coverage_config_x86_64.json](https://github.com/rust-vmm/crate-template/blob/main/coverage_config_x86_64.json).

**Comment by stefano-garzarella** [comment]
CODEOWNERS now is valid, and the rest should be addressed by #8.

@epilys right?

**Comment by epilys** [comment]
That's right!

**Comment by epilys** [comment]
Fixed in #8
