### ISSUE TITLE
What are the plans for xen-sys?

### ISSUE THREAD

**Issue by algermissen** [rust-vmm/xen-sys#7]
Hi,
I am looking into options to write unikernels for xen in Rust and came across xen-sys. 

Can you provide some insights into the status of the repo and future plans or if it has been continued elsewhere.

Jan

**Comment by mathieupoirier** [comment]
Hi Jen,

The rust-vmm/xen-sys crate is currently a place holder and is hosting a version of the project that dates from a few years back.  The lastest code can be found [here](https://github.com/mathieupoirier/xen-sys).  Support for aarch64 along with an API to interact with Xen what added over the last 18 months.  You will also find there an x86_64 and aarch64 unikernel that are ready to go.  

I am currently working on building a proper CI for the xen-sys crate.  Once that is in place I will start moving code from the repository pointed to above to the official rust-vmm/xen-sys repository here.

I would love to see this code getting exposure outside of my own project so feel free to get back to me with questions.

Thanks,
Mathieu

**Comment by algermissen** [comment]
@mathieupoirier Thanks very much - that helps a lot.
